import { Fixture, Operator } from "@/types";

export const OPS_USERS: Operator[] = [
    { name: "DUYGU", email: "duygu@gnbmar.com", role: "Operator" },
    { name: "BERK", email: "berk@gnbmar.com", role: "Manager" },
    { name: "GUROL", email: "gurol@gnbmar.com", role: "Broker" },
    { name: "YOAN", email: "yoan@gnbmar.com", role: "Broker" },
    { name: "OZGUR", email: "ozgur@gnbmar.com", role: "Broker" },
    { name: "BATU", email: "batu@gnbmar.com", role: "Broker" },
    { name: "EMRE", email: "emre@gnbmar.com", role: "Broker" }
];

export const MOCK_FIXTURES: Fixture[] = [
    {
        id: "FX-83921",
        no: "FX-83921",
        vessel: "MT CHEMICAL PIONEER",
        broker: "BERK",
        coBroker: "",
        operator: "DUYGU",
        cpDate: "2024-03-10",
        layFrom: "2024-03-15",
        layFromTime: "16:00",
        layTo: "2024-03-18",
        layToTime: "23:59",
        loadPort: "ISTANBUL",
        dischPort: "ROTTERDAM",
        cargo: "METHANOL",
        product: "METHANOL",
        quantity: "5000",
        ccy: "USD",
        charterer: "ABC CHEMICALS",
        owner: "GLOBAL TANKERS",
        freight: "45",
        payment: "PREPAID",
        cpForm: "ASBATANKVOY",
        commission: "1.25",
        notes: "Urgent shipment",
        shipper: "",
        receiver: "",
        blQty: "",
        hasDem: false,
        demRate: "",
        agreedLt: "",
        demCcy: "USD",
        demAmt: "",
        demInitialAmt: "",
        demDiscountedAmt: "",
        demStatus: "Unpaid",
        claimRec: "",
        claimFwd: "",
        archived: false,
        cancelled: false
    },
    {
        id: "FX-83922",
        no: "FX-83922",
        vessel: "MT OCEAN STAR",
        broker: "GUROL", // Dubai broker
        coBroker: "",
        operator: "BERK",
        cpDate: "2024-03-12",
        layFrom: "2024-03-20",
        layFromTime: "16:00",
        layTo: "2024-03-22",
        layToTime: "23:59",
        loadPort: "JEBEL ALI",
        dischPort: "MUMBAI",
        cargo: "BASE OIL",
        product: "BASE OIL",
        quantity: "3000",
        ccy: "USD",
        charterer: "XYZ TRADING",
        owner: "STAR SHIPPING",
        freight: "30",
        payment: "COD",
        cpForm: "ASBATANKVOY",
        commission: "1.25",
        notes: "",
        shipper: "",
        receiver: "",
        blQty: "",
        hasDem: true,
        demRate: "12000",
        agreedLt: "48",
        demCcy: "USD",
        demAmt: "",
        demInitialAmt: "",
        demDiscountedAmt: "",
        demStatus: "Unpaid",
        claimRec: "",
        claimFwd: "",
        archived: false,
        cancelled: false
    },
    {
        id: "FX-83923",
        no: "FX-83923",
        vessel: "MT AEGEAN BREEZE",
        broker: "DUYGU",
        coBroker: "",
        operator: "BERK",
        cpDate: "2024-01-14", // Old date -> likely finished
        layFrom: "2024-01-25",
        layFromTime: "16:00",
        layTo: "2024-01-28",
        layToTime: "23:59",
        loadPort: "IZMIR",
        dischPort: "BARCELONA",
        cargo: "VEG OIL",
        product: "SUNFLOWER OIL",
        quantity: "6000",
        ccy: "EUR",
        charterer: "FOOD CORP",
        owner: "AEGEAN MARITIME",
        freight: "55",
        payment: "NET 30",
        cpForm: "ASBATANKVOY",
        commission: "1.25",
        notes: "",
        shipper: "",
        receiver: "",
        blQty: "",
        hasDem: false,
        demRate: "",
        agreedLt: "",
        demCcy: "USD",
        demAmt: "",
        demInitialAmt: "",
        demDiscountedAmt: "",
        demStatus: "Paid",
        claimRec: "",
        claimFwd: "",
        archived: true,
        cancelled: false
    }
];
