import { Fixture } from "@/types";

export const FIXTURE_LIST_DATA: Fixture[] = [
  {
    id: "FL-1",
    no: "9",
    vessel: "GUNECE",
    broker: "OZGUR",
    coBroker: "",
    operator: "BERK",
    cpDate: "2026-02-16",
    layFrom: "2026-03-02",
    layFromTime: "16:00",
    layTo: "2026-03-04",
    layToTime: "23:59",
    loadPort: "PORT SAID",
    dischPort: "YUMURTALIK",
    cargo: "CSS",
    product: "",
    quantity: "in 5,500 mts 1 grade CSS upto fcc in chopt (max 5,700 mts)",
    ccy: "USD",
    charterer: "KOLMAR",
    owner: "BEYKAR",
    freight: "27.50 USD",
    payment: "PMT",
    cpForm: "LATEST 1 BD ARR. AT DP",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-2",
    no: "5",
    vessel: "BOW SAGA",
    broker: "GUROL",
    coBroker: "YOAN",
    operator: "BERK",
    cpDate: "2026-02-10",
    layFrom: "2026-02-07",
    layFromTime: "16:00",
    layTo: "2026-02-09",
    layToTime: "23:59",
    loadPort: "MESAIEED / JUBAIL",
    dischPort: "PORT KHALIFA",
    cargo: "CSS AWVNS",
    product: "",
    quantity: "40000 mts",
    ccy: "USD",
    charterer: "EGA",
    owner: "ODJFELL",
    freight: "PMT",
    payment: "PMT",
    cpForm: "BBB",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-3",
    no: "2",
    vessel: "SEA HARVEST",
    broker: "YOAN",
    coBroker: "",
    operator: "BERK",
    cpDate: "2026-01-29",
    layFrom: "2026-02-02",
    layFromTime: "16:00",
    layTo: "2026-02-04",
    layToTime: "23:59",
    loadPort: "MESAIEED",
    dischPort: "PORT KHALIFA",
    cargo: "CSS",
    product: "",
    quantity: "",
    ccy: "USD",
    charterer: "EGA",
    owner: "SC SHIPPING",
    freight: "USD 220k Lsum BSS 1/1 all inclusive",
    payment: "LMSUM",
    cpForm: "ASBATANKVOY",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-4",
    no: "8",
    vessel: "BLUE BIRD",
    broker: "BATU",
    coBroker: "OZGUR",
    operator: "DUYGU",
    cpDate: "2026-02-13",
    layFrom: "2026-02-15",
    layFromTime: "16:00",
    layTo: "2026-02-16",
    layToTime: "23:59",
    loadPort: "BOURGAS",
    dischPort: "CONSTANTA",
    cargo: "Gasoline WVNS CLN",
    product: "",
    quantity: "Min 6,500 MT (max 10,800 m3)",
    ccy: "USD",
    charterer: "SAKSA",
    owner: "ARMADOR",
    freight: "",
    payment: "PMT",
    cpForm: "BBB",
    commission: "0.05",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-5",
    no: "7",
    vessel: "BANDIRMA",
    broker: "OZGUR",
    coBroker: "",
    operator: "BERK",
    cpDate: "2026-02-13",
    layFrom: "2026-02-25",
    layFromTime: "16:00",
    layTo: "2026-02-27",
    layToTime: "23:59",
    loadPort: "PORT SAID",
    dischPort: "DERINCE",
    cargo: "Caustic Soda Solution",
    product: "",
    quantity: "Min 8,000 MT / 1 Grade",
    ccy: "USD",
    charterer: "KOLMAR",
    owner: "HICRI ERCILI",
    freight: "",
    payment: "PMT",
    cpForm: "ASBATANKVOY",
    commission: "2.5%",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-6",
    no: "4",
    vessel: "HEAVEN",
    broker: "GUROL",
    coBroker: "",
    operator: "DUYGU",
    cpDate: "2026-02-06",
    layFrom: "2026-02-07",
    layFromTime: "16:00",
    layTo: "2026-02-09",
    layToTime: "23:59",
    loadPort: "YANBU",
    dischPort: "ENNORE",
    cargo: "LAB / 1 Grade",
    product: "",
    quantity: "3,000 MT 5% Molco",
    ccy: "USD",
    charterer: "FARABI",
    owner: "MOL",
    freight: "",
    payment: "PMT",
    cpForm: "ASBATANKVOY",
    commission: "2.5%",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-7",
    no: "3",
    vessel: "BONITA AKI",
    broker: "YOAN",
    coBroker: "GUROL",
    operator: "DUYGU",
    cpDate: "2026-02-03",
    layFrom: "2026-02-10",
    layFromTime: "16:00",
    layTo: "2026-02-15",
    layToTime: "23:59",
    loadPort: "YANBU",
    dischPort: "EL DEKHEILA / ISKENDERUN / ORAN / ANTWERP (CHOPT DAGENHAM)",
    cargo: "LAB 1 Grade 5% Molco",
    product: "",
    quantity: "",
    ccy: "USD",
    charterer: "FARABI",
    owner: "MOL",
    freight: "",
    payment: "",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-8",
    no: "4",
    vessel: "CHEMICAL MASTER",
    broker: "BATU",
    coBroker: "",
    operator: "DUYGU",
    cpDate: "2026-01-23",
    layFrom: "2026-02-02",
    layFromTime: "16:00",
    layTo: "2026-02-06",
    layToTime: "23:59",
    loadPort: "ROTTERDAM / ANTWERP",
    dischPort: "DERINCE",
    cargo: "Methylene Chloride (DCM)",
    product: "",
    quantity: "1,500 MT / 1 Grade",
    ccy: "USD",
    charterer: "IZOMER",
    owner: "CHEMSHIP",
    freight: "",
    payment: "PMT",
    cpForm: "",
    commission: "2.5%",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-9",
    no: "1",
    vessel: "KOREA CHEMI",
    broker: "YOAN",
    coBroker: "",
    operator: "DUYGU",
    cpDate: "2026-01-12",
    layFrom: "2026-01-24",
    layFromTime: "16:00",
    layTo: "2026-01-27",
    layToTime: "23:59",
    loadPort: "JUBAIL",
    dischPort: "JEBEL ALI / WCI",
    cargo: "SM (Styrene Monomer) WVNS",
    product: "",
    quantity: "5,000 MT 5% Molco / 1 Grade",
    ccy: "USD",
    charterer: "PETROCHEM",
    owner: "DM SHIPPING",
    freight: "",
    payment: "PMT",
    cpForm: "BBB",
    commission: "2.5%",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-10",
    no: "1",
    vessel: "FORTUO",
    broker: "EMRE",
    coBroker: "",
    operator: "BERK",
    cpDate: "2026-01-07",
    layFrom: "2026-02-20",
    layFromTime: "16:00",
    layTo: "2026-02-25",
    layToTime: "23:59",
    loadPort: "BELAWAN / DUMAI / LUBUK GAUNG / PASIR GUDANG",
    dischPort: "TAMAN",
    cargo: "Palm Oil Products",
    product: "",
    quantity: "Min 35,000 MT upto FCC / AWVNS",
    ccy: "USD",
    charterer: "GREEN SUPPLIERS",
    owner: "STAMINA SHIPPING",
    freight: "",
    payment: "PMT",
    cpForm: "BBB",
    commission: "1.25%",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "FL-11",
    no: "50",
    vessel: "ALANGOVA",
    broker: "GUROL",
    coBroker: "",
    operator: "DUYGU",
    cpDate: "2025-12-31",
    layFrom: "2026-01-10",
    layFromTime: "16:00",
    layTo: "2026-01-15",
    layToTime: "23:59",
    loadPort: "YANBU",
    dischPort: "ISKENDERUN / GEBZE / ORAN / JORF LASFAR / HOUSTON / ALTAMIRA",
    cargo: "LAB / 1 Grade",
    product: "",
    quantity: "Upto FCC (~10,600 MT)",
    ccy: "USD",
    charterer: "FARABI",
    owner: "TUNE CHEMICAL",
    freight: "",
    payment: "LMSUM",
    cpForm: "BBB",
    commission: "2.5%",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
];

export const ISTANBUL_DATA: Fixture[] = [
  {
    id: "IST-1",
    no: "1",
    vessel: "FORTUO",
    broker: "EMRE",
    coBroker: "",
    operator: "BERK",
    cpDate: "2026-01-07",
    layFrom: "2026-02-20",
    layFromTime: "16:00",
    layTo: "2026-02-25",
    layToTime: "23:59",
    loadPort: "BELAWAN / DUMAI / LUBUK GAUNG / PASIR GUDANG",
    dischPort: "TAMAN",
    cargo: "Palm Oil Products",
    product: "Min 35,000 MT upto FCC / AWVNS",
    quantity: "",
    ccy: "USD",
    charterer: "GREEN SUPPLIERS",
    owner: "STAMINA SHIPPING",
    freight: "PMT",
    payment: "",
    cpForm: "",
    commission: "1.25",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "IST-2",
    no: "2",
    vessel: "MED PAKIZE",
    broker: "EMRE",
    coBroker: "OZGUR",
    operator: "DUYGU",
    cpDate: "2026-01-08",
    layFrom: "2025-12-09",
    layFromTime: "16:00",
    layTo: "2025-12-11",
    layToTime: "23:59",
    loadPort: "HAMBURG",
    dischPort: "LIVORNO",
    cargo: "LUBES",
    product: "",
    quantity: "MIN 2,000 MTS UPTO 2,200 MTS",
    ccy: "USD",
    charterer: "GREENEX",
    owner: "YMN TANKER",
    freight: "USD 300,000 LSUM BSS 1:1",
    payment: "LMSUM",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "IST-3",
    no: "3",
    vessel: "VIVA",
    broker: "OZGUR",
    coBroker: "",
    operator: "BERK",
    cpDate: "",
    layFrom: "",
    layFromTime: "16:00",
    layTo: "",
    layToTime: "23:59",
    loadPort: "PORT SAID",
    dischPort: "DERINCE",
    cargo: "",
    product: "CSS",
    quantity: "",
    ccy: "USD",
    charterer: "KOLMAR",
    owner: "MIBER",
    freight: "",
    payment: "",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "IST-4",
    no: "4",
    vessel: "CHEMICAL MASTER",
    broker: "BATU",
    coBroker: "",
    operator: "DUYGU",
    cpDate: "2026-01-23",
    layFrom: "2026-02-02",
    layFromTime: "16:00",
    layTo: "2026-02-06",
    layToTime: "23:59",
    loadPort: "ROTTERDAM / ANTWERP",
    dischPort: "DERINCE",
    cargo: "Methylene Chloride (DCM)",
    product: "1,500 MT / 1 Grade",
    quantity: "",
    ccy: "USD",
    charterer: "IZOMER",
    owner: "CHEMSHIP",
    freight: "PMT",
    payment: "",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "IST-5",
    no: "5",
    vessel: "MUSTAFA NECATI",
    broker: "BATU",
    coBroker: "OZGUR",
    operator: "DUYGU",
    cpDate: "2026-01-27",
    layFrom: "2026-01-29",
    layFromTime: "16:00",
    layTo: "2026-01-29",
    layToTime: "23:59",
    loadPort: "BOURGAS",
    dischPort: "CONSTANTA",
    cargo: "GASOILNE",
    product: "GASOILNE",
    quantity: "min 5000 mts up to fcc",
    ccy: "USD",
    charterer: "SAKSA",
    owner: "STATU GEMI",
    freight: "25 USD PMT",
    payment: "PMT",
    cpForm: "",
    commission: "5.0",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "IST-6",
    no: "6",
    vessel: "ELARA",
    broker: "BATU",
    coBroker: "OZGUR",
    operator: "DUYGU",
    cpDate: "2026-02-03",
    layFrom: "",
    layFromTime: "16:00",
    layTo: "",
    layToTime: "23:59",
    loadPort: "BOURGAS",
    dischPort: "CONSTANTA",
    cargo: "Gasoline",
    product: "Min 5000 Mts Up To Fcc In Chopt,",
    quantity: "Usd 24.00 Pmt Bss 1-1 Min/Max 5000mts",
    ccy: "USD",
    charterer: "SAKSA",
    owner: "MIBER",
    freight: "PMT",
    payment: "",
    cpForm: "",
    commission: "5.0",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "IST-7",
    no: "7",
    vessel: "BANDIRMA",
    broker: "OZGUR",
    coBroker: "",
    operator: "BERK",
    cpDate: "2026-02-13",
    layFrom: "2026-02-25",
    layFromTime: "16:00",
    layTo: "2026-02-27",
    layToTime: "23:59",
    loadPort: "PORT SAID",
    dischPort: "DERINCE",
    cargo: "Caustic Soda Solution",
    product: "Min 8,000 MT / 1 Grade",
    quantity: "",
    ccy: "USD",
    charterer: "KOLMAR",
    owner: "KOLMAR",
    freight: "PMT",
    payment: "",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "IST-8",
    no: "8",
    vessel: "BLUE BIRD",
    broker: "BATU",
    coBroker: "OZGUR",
    operator: "DUYGU",
    cpDate: "2026-02-13",
    layFrom: "2026-02-15",
    layFromTime: "16:00",
    layTo: "2026-02-16",
    layToTime: "23:59",
    loadPort: "BOURGAS",
    dischPort: "CONSTANTA",
    cargo: "Gasoline WVNS CLN",
    product: "Min 6,500 MT (max 10,800 m3)",
    quantity: "",
    ccy: "USD",
    charterer: "SAKSA",
    owner: "ARMADOR",
    freight: "PMT",
    payment: "",
    cpForm: "",
    commission: "5.0",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "IST-9",
    no: "9",
    vessel: "GUNECE",
    broker: "OZGUR",
    coBroker: "",
    operator: "BERK",
    cpDate: "2026-02-16",
    layFrom: "2026-03-02",
    layFromTime: "16:00",
    layTo: "2026-03-04",
    layToTime: "23:59",
    loadPort: "PORT SAID",
    dischPort: "YUMURTALIK",
    cargo: "CSS",
    product: "CSS",
    quantity: "in 5,500 mts 1 grade CSS upto fcc in chopt (max 5,700 mts)",
    ccy: "USD",
    charterer: "KOLMAR",
    owner: "BEYKAR",
    freight: "27.50 USD",
    payment: "PMT",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
];

export const DUBAI_DATA: Fixture[] = [
  {
    id: "DUB-1",
    no: "1",
    vessel: "KOREA CHEMI",
    broker: "GUROL",
    coBroker: "",
    operator: "DUYGU",
    cpDate: "2026-01-12",
    layFrom: "2026-01-24",
    layFromTime: "16:00",
    layTo: "2026-01-27",
    layToTime: "23:59",
    loadPort: "JUBAIL",
    dischPort: "JEBEL ALI / WCI",
    cargo: "SM (Styrene Monomer) WVNS",
    product: "5,000 MT 5% Molco / 1 Grade",
    quantity: "",
    ccy: "USD",
    charterer: "PETROCHEM",
    owner: "DM SHIPPING",
    freight: "PMT",
    payment: "",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "DUB-2",
    no: "2",
    vessel: "SEA HARVEST",
    broker: "YOAN",
    coBroker: "",
    operator: "BERK",
    cpDate: "2026-01-29",
    layFrom: "2026-02-02",
    layFromTime: "16:00",
    layTo: "2026-02-04",
    layToTime: "23:59",
    loadPort: "MESAIEED",
    dischPort: "PORT KHALIFA",
    cargo: "CSS",
    product: "18,898 MT",
    quantity: "",
    ccy: "USD",
    charterer: "EGA",
    owner: "SC SHIPPING",
    freight: "USD 220k Lsum BSS 1/1 all inclusive",
    payment: "LMSUM",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "DUB-3",
    no: "3",
    vessel: "BONITA AKI",
    broker: "YOAN",
    coBroker: "GUROL",
    operator: "DUYGU",
    cpDate: "2026-02-03",
    layFrom: "2026-02-10",
    layFromTime: "16:00",
    layTo: "2026-02-15",
    layToTime: "23:59",
    loadPort: "YANBU",
    dischPort: "EL DEKHEILA / ISKENDERUN / ORAN / ANTWERP (CHOPT DAGENHAM)",
    cargo: "LAB 1 Grade 5% Molco",
    product: "LAB",
    quantity: "",
    ccy: "USD",
    charterer: "FARABI",
    owner: "MOL",
    freight: "",
    payment: "",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "DUB-4",
    no: "4",
    vessel: "HEAVEN",
    broker: "GUROL",
    coBroker: "",
    operator: "DUYGU",
    cpDate: "2026-02-06",
    layFrom: "2026-02-07",
    layFromTime: "16:00",
    layTo: "2026-02-09",
    layToTime: "23:59",
    loadPort: "YANBU",
    dischPort: "ENNORE",
    cargo: "LAB / 1 Grade",
    product: "3,000 MT 5% Molco",
    quantity: "",
    ccy: "USD",
    charterer: "FARABI",
    owner: "MOL",
    freight: "PMT",
    payment: "",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "DUB-5",
    no: "5",
    vessel: "BOW SAGA",
    broker: "GUROL",
    coBroker: "YOAN",
    operator: "BERK",
    cpDate: "2026-02-10",
    layFrom: "2026-02-07",
    layFromTime: "16:00",
    layTo: "2026-02-09",
    layToTime: "23:59",
    loadPort: "MESAIEED / JUBAIL",
    dischPort: "PORT KHALIFA",
    cargo: "CSS AWVNS",
    product: "40,000 MT (2 × 20,000 MT 5% Molco)",
    quantity: "40000 mts",
    ccy: "USD",
    charterer: "EGA",
    owner: "ODJFELL",
    freight: "PMT",
    payment: "PMT",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
  {
    id: "DUB-6",
    no: "6",
    vessel: "GOLDEN SAPLING",
    broker: "GUROL",
    coBroker: "",
    operator: "DUYGU",
    cpDate: "2026-02-12",
    layFrom: "2026-02-20",
    layFromTime: "16:00",
    layTo: "2026-02-25",
    layToTime: "23:59",
    loadPort: "JUBAIL",
    dischPort: "ADABIYAH / GEBZE-IZMIT RNG",
    cargo: "VAM / Chems 5% Molco",
    product: "8,600 MT",
    quantity: "",
    ccy: "USD",
    charterer: "SIPCHEM",
    owner: "CHEMPOOL",
    freight: "PMT",
    payment: "",
    cpForm: "",
    commission: "2.5",
    notes: "",
    shipper: "",
    receiver: "",
    blQty: "",
    hasDem: false,
    demRate: "",
    agreedLt: "",
    demCcy: "",
    demAmt: "",
    demInitialAmt: "",
    demDiscountedAmt: "",
    demStatus: "Unpaid",
    claimRec: "",
    claimFwd: "",
    archived: false,
    cancelled: false,
  },
];

export const IST_DEMURRAGE_DATA: Fixture[] = [
];

export const DUB_DEMURRAGE_DATA: Fixture[] = [
];

export const ALL_FIXTURES: Fixture[] = [...FIXTURE_LIST_DATA];

export const OPS_USERS = [
  { name: "BERK", email: "berk@gnbmar.com", role: "Operator" },
  { name: "DUYGU", email: "duygu@gnbmar.com", role: "Operator" },
  { name: "GIZEM", email: "gizem@gnbmar.com", role: "Operator" },
  { name: "EZGI", email: "ezgi@gnbmar.com", role: "Operator" },
  { name: "BATU", email: "batu@gnbmar.com", role: "Broker" },
  { name: "EMRE", email: "emre@gnbmar.com", role: "Broker" },
  { name: "GUROL", email: "gurol@gnbmar.com", role: "Broker" },
  { name: "OZGUR", email: "ozgur@gnbmar.com", role: "Broker" },
  { name: "YOAN", email: "yoan@gnbmar.com", role: "Broker" },
];